### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by enigmatic-user**
Translated missing phrases to German

### CODE REVIEW

**Comment by silentworks** [comment]
Formz is no longer maintained by me, please send all PRs to https://github.com/Adido/formz repo instead. Plus you might want to create a directory for the German (de) translation instead of replacing English (en) translation.

**Comment by enigmatic-user** [comment]
Thanks for the link to the new repo.

Regarding the directory for the German translation (de): It already existed, and I just changed English phrases in the German language file to German. Just take a look at the path... I completely translated Revo plus several Extras, so I'm not that inexperienced.  ;)

**Comment by silentworks** [comment]
You are indeed correct about the path, it was google translate in chrome that somehow translated the de in the path to en. Sorry about that.

**Comment by enigmatic-user** [comment]
No problem. Seems to be a tricky technology...  ;)

**Pull request closed without merging**
